name: 'Terraform import pipeline for data-collection system'

on:
  push:
    branches: ["feature/s3-buckets-config" ]
  pull_request:
    branches: ["feature/s3-buckets-config" ]

env:
  STAGE: development
  TERRAFORM_VERSION: 1.7.3
  SYSTEM_DIR: systems/data-collection

permissions:
    contents: read

jobs:
    terraform:
        name: 'Terraform'
        runs-on: ubuntu-latest
        environment: development

        defaults:
            run:
                shell: bash
                working-directory: ${{ env.SYSTEM_DIR }}

        steps:
          - name: Checkout
            uses: actions/checkout@v4

          - name: Setup Workspace
            run: |
              echo "Environment variables:"
              echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
              echo "Current directory: $(pwd)"

          - name: Install tfenv
            run: |
              git clone --depth=1 https://github.com/tfutils/tfenv.git $GITHUB_WORKSPACE/.bin/tfenv
              chmod +x $GITHUB_WORKSPACE/.bin/tfenv/bin/*
              echo "$GITHUB_WORKSPACE/.bin/tfenv/bin" >> $GITHUB_PATH
              $GITHUB_WORKSPACE/.bin/tfenv/bin/tfenv install $TERRAFORM_VERSION
              $GITHUB_WORKSPACE/.bin/tfenv/bin/tfenv use $TERRAFORM_VERSION
              echo "Verifying terraform installation..."
              $GITHUB_WORKSPACE/.bin/tfenv/bin/terraform --version

          - name: Install pre-commit
            run: |
              python -m pip install pre-commit
              pre-commit install

          - name: Install ECS CLI
            run: |
              mkdir -p $GITHUB_WORKSPACE/.bin
              curl -o $GITHUB_WORKSPACE/.bin/ecs https://amazon-ecs-cli.s3.amazonaws.com/ecs-cli-linux-amd64-latest
              chmod +x $GITHUB_WORKSPACE/.bin/ecs
              echo "$GITHUB_WORKSPACE/.bin" >> $GITHUB_PATH

          - name: Set up AWS CLI
            uses: aws-actions/configure-aws-credentials@v4
            with:
              aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
              aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
              aws-region: eu-west-2

          - name: Authenticate with GitHub CLI
            run: |
              if ! gh auth status --hostname github.com > /dev/null 2>&1; then
                echo "Not authenticated. Logging in..."
                gh auth login --hostname github.com --web --git-protocol ssh --skip-ssh-key --scopes user:email
              else
                echo "Already authenticated with GitHub CLI."
              fi
              echo "GITHUB_TOKEN=$(gh auth token --hostname github.com)" >> $GITHUB_ENV

          - name: Check Config Files
            run: |
              echo "Current directory: $(pwd)"
              echo "Checking for configuration files..."
              ls -la environments/

              if [ ! -f "environments/${{ env.STAGE }}.tfvars" ]; then
                echo "Error: environments/${{ env.STAGE }}.tfvars not found"
                ls -la environments/
                exit 1
              fi
              if [ ! -f "environments/${{ env.STAGE }}.tfbackend" ]; then
                echo "Error: environments/${{ env.STAGE }}.tfbackend not found"
                ls -la environments/
                exit 1
              fi

              echo "Verifying access to S3 backend bucket..."
              aws s3 ls s3://digital-land-terraform-remote-state/ --recursive
              if [ $? -ne 0 ]; then
                echo "Error: Unable to access S3 bucket. Check AWS credentials and permissions."
                exit 1
              fi
          - name: Check Existing AWS Resources
            run: |

              echo "Verifying access to S3 backend bucket..."
              aws s3 ls s3://development-pyspark-jobs-logs/ 
              if [ $? -ne 0 ]; then
                echo "Error: Unable to access S3 bucket. Check AWS credentials and permissions."
                exit 1
              fi

              echo "Verifying access to Athena..."
              aws athena list-work-groups

          - name: Install dependencies for make
            run: sudo apt-get update && sudo apt-get install -y make

          - name: Clean build artifacts using make
            run: |
              echo "Current directory: $(pwd)"
              make clean

          - name: Terraform Init
            run: |
              echo "Running terraform version check..."
              terraform --version

              echo "Checking paths..."
              echo "Current directory: $(pwd)"

              echo "Initializing terraform for data-collection system..."

              echo "Running terraform init with backend config..."
              TF_LOG=DEBUG terraform init \
                -var-file "environments/${{ env.STAGE }}..tfvars" \
                -backend-config="environments/${{ env.STAGE }}.tfbackend" \
                -reconfigure

              echo "Showing current terraform state..."
              terraform show

          - name: Terraform Format
            run: terraform fmt -check

        #   - name: Terraform Refresh State
        #     if: github.event_name == 'push'
        #     run: |
        #       echo "Running terraform refresh..."
        #       terraform refresh -var-file="environments/${{ env.STAGE }}.tfvars" -no-color

          - name: Terraform Plan
            id: plan
            run: |
              echo "Running terraform plan..."

              echo "Verifying working directory:"
              pwd

              echo "Running terraform validate..."
              terraform validate

              echo "Running plan with variables..."
              # TF_LOG=DEBUG terraform plan -var-file="environments/${{ env.STAGE }}.tfvars" -out="tfplan.out" -no-color
              terraform plan \
              -generate-config-out=generated.tf \
              -var-file="environments/${{ env.STAGE }}.tfvars"

              # echo "Verifying terraform plan output:"
              # terraform show -no-color tfplan.out

          - name: List files
            run: ls -la

          - name: Upload generated.tf artifact
            if: always()
            uses: actions/upload-artifact@v4
            with:
                name: generated.tf
                path: ${{ env.SYSTEM_DIR }}/generated.tf

          - name: Download generated.tf artifact
            uses: actions/download-artifact@v5
            with:
                name: generated.tf
          - name: Test artifact download
            run: |
              echo "Listing files in current directory:"
              ls -la
              if [ -f "generated.tf" ]; then
                echo "generated.tf file exists."
              else
                echo "Error: generated.tf file does not exist."
                exit 1
              fi
          - name: Display generated.tf content
            run: |
              echo "Contents of generated.tf:"
              cat generated.tf

          # - name: Terraform Apply
          #   if: github.ref == 'refs/heads/feature/fix-ghactions-pipeline' && github.event_name == 'push'
          #   run: |
          #     echo "Running terraform apply..."
          #     terraform apply -var-file="environments/${{ env.STAGE }}.tfvars" -auto-approve -no-color

        #   - name: Terraform Output
        #     if: success()
        #     run: |
        #       echo "Getting terraform outputs..."
        #       terraform output -json
